###
GET http://localhost:8888/products/

###
GET http://localhost:8888/product/4f17dbd7-32bf-4b13-b744-c335f5fed86a

###
POST http://localhost:8888/products/
Content-Type:application/json

{
    "name": "Mouse Gamer Razer",
    "price": 177.60
}

###
POST http://localhost:8888/products/
Content-Type:application/json

{
    "name": "Teclado Gamer Logitech G213",
    "price": 366.89
}

###
POST http://localhost:8888/products/
Content-Type:application/json

{
    "name": "Cadeira Gamer TGT Heron TC",
    "price": 399.99
}
