###
GET http://localhost:8888/products/

###
GET http://localhost:8888/product/829a2f2c-b193-49c5-835f-3c383c33d445

###
POST http://localhost:8888/products/
Content-Type:application/json

{
    "name": "Mouse Gamer Razer",
    "price": 177.60
}

###
POST http://localhost:8888/products/
Content-Type:application/json

{
    "name": "Teclado Gamer Logitech G213",
    "price": 366.89
}

###
POST http://localhost:8888/products/
Content-Type:application/json

{
    "name": "Cadeira Gamer TGT Heron TC",
    "price": 399.99
}

###
PUT http://localhost:8888/products/10fe3178-464a-421c-8aaf-7b6bdb9eb8e8
Content-Type:application/json

{
    "name": "Cadeira Gamer TGT Heron TC",
    "price": 400,
    "quantity": 10
}